-- Poll question bank (ported from the Lovable seed migration).
-- Idempotent: re-running adds nothing.
INSERT INTO poll_questions (id, text, category) SELECT 'ff39006a-99d3-4d21-9cf7-37f444f2ce5e', 'Most likely to start a cult', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to start a cult');
INSERT INTO poll_questions (id, text, category) SELECT 'bb929d83-ef8a-4343-8d09-6a2c330870fa', 'Most likely to text back at 3am', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to text back at 3am');
INSERT INTO poll_questions (id, text, category) SELECT 'd63f3e28-a1bf-41f5-a242-3a58a6cd2101', 'Has the best music taste', 'taste' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Has the best music taste');
INSERT INTO poll_questions (id, text, category) SELECT 'f9be07b4-4dd4-4cd0-a747-7b8b889e3f41', 'Would survive longest in a zombie apocalypse', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Would survive longest in a zombie apocalypse');
INSERT INTO poll_questions (id, text, category) SELECT '0de8ff81-ffa0-4c74-ba85-9147bbf4ee9e', 'Most likely to glow up in college', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to glow up in college');
INSERT INTO poll_questions (id, text, category) SELECT '08914829-377b-459e-8078-46b25bade006', 'Would make the best road trip co-pilot', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Would make the best road trip co-pilot');
INSERT INTO poll_questions (id, text, category) SELECT '8da606a2-9d7f-4ec2-a1e7-4771bf84d443', 'Has the most underrated style', 'taste' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Has the most underrated style');
INSERT INTO poll_questions (id, text, category) SELECT 'c2c5aed1-b45a-419f-b292-fa4d59470ce0', 'Most likely to become famous on TikTok', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to become famous on TikTok');
INSERT INTO poll_questions (id, text, category) SELECT 'db6c063c-b4b6-4b5e-89a5-5b94f1239c02', 'Best person to share secrets with', 'wholesome' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Best person to share secrets with');
INSERT INTO poll_questions (id, text, category) SELECT 'c61b48e6-7db1-413d-82ec-14e8c57c9ff4', 'Most likely to spontaneously book a flight', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to spontaneously book a flight');
INSERT INTO poll_questions (id, text, category) SELECT '98d0de3a-ff42-4b9b-bd20-b36717a218be', 'Looks like they tell the funniest stories', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Looks like they tell the funniest stories');
INSERT INTO poll_questions (id, text, category) SELECT '3b45e3d0-389e-455f-b976-20f32c8531c5', 'Most likely to ace a vibe check', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to ace a vibe check');
INSERT INTO poll_questions (id, text, category) SELECT 'ec64c231-1401-4354-8c66-9ac3729dd5da', 'Best aesthetic on their feed', 'taste' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Best aesthetic on their feed');
INSERT INTO poll_questions (id, text, category) SELECT 'ad91eb56-7c70-4a40-9fe8-526e01aa1b05', 'Most likely to fall in love this year', 'wholesome' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to fall in love this year');
INSERT INTO poll_questions (id, text, category) SELECT '2d90e904-9051-4959-8578-41082365b8cc', 'Could probably beat me in a dance battle', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Could probably beat me in a dance battle');
INSERT INTO poll_questions (id, text, category) SELECT '745697a0-0b21-45f7-ad2b-24a4aa947d35', 'Most likely to start a podcast nobody asked for', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to start a podcast nobody asked for');
INSERT INTO poll_questions (id, text, category) SELECT 'c526deda-b713-4538-90b6-fece44679084', 'Would write you back the loveliest birthday message', 'wholesome' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Would write you back the loveliest birthday message');
INSERT INTO poll_questions (id, text, category) SELECT '9c90321f-cf9f-41d4-b55a-bc6a6de6287a', 'Has main character energy', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Has main character energy');
INSERT INTO poll_questions (id, text, category) SELECT '5a379170-843c-47c5-b160-f17b13b50b33', 'Most likely to disappear and become a chef in Italy', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Most likely to disappear and become a chef in Italy');
INSERT INTO poll_questions (id, text, category) SELECT '173a21bb-6b47-4e63-b737-25802bd08615', 'Person you''d want on your trivia team', 'fun' WHERE NOT EXISTS (SELECT 1 FROM poll_questions WHERE text = 'Person you''d want on your trivia team');
