/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OnboardingQuizRouteImport } from './routes/onboarding.quiz'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppStandingsRouteImport } from './routes/app.standings'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppAddRouteImport } from './routes/app.add'
import { Route as ApiIgAvatarRouteImport } from './routes/api.ig-avatar'
import { Route as AppMatchIdRouteImport } from './routes/app.match.$id'
import { Route as AppGroupIdRouteImport } from './routes/app.group.$id'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as ApiAvatarSplatRouteImport } from './routes/api.avatar.$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api.public.payments.webhook'
import { Route as ApiPublicHooksWeeklySuperlativeRouteImport } from './routes/api.public.hooks.weekly-superlative'
import { Route as ApiPublicHooksMatchExpiryRouteImport } from './routes/api.public.hooks.match-expiry'
import { Route as ApiPublicHooksDailyPollRouteImport } from './routes/api.public.hooks.daily-poll'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingQuizRoute = OnboardingQuizRouteImport.update({
  id: '/onboarding/quiz',
  path: '/onboarding/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppStandingsRoute = AppStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const ApiIgAvatarRoute = ApiIgAvatarRouteImport.update({
  id: '/api/ig-avatar',
  path: '/api/ig-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMatchIdRoute = AppMatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupIdRoute = AppGroupIdRouteImport.update({
  id: '/group/$id',
  path: '/group/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAvatarSplatRoute = ApiAvatarSplatRouteImport.update({
  id: '/api/avatar/$',
  path: '/api/avatar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklySuperlativeRoute =
  ApiPublicHooksWeeklySuperlativeRouteImport.update({
    id: '/api/public/hooks/weekly-superlative',
    path: '/api/public/hooks/weekly-superlative',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatchExpiryRoute =
  ApiPublicHooksMatchExpiryRouteImport.update({
    id: '/api/public/hooks/match-expiry',
    path: '/api/public/hooks/match-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyPollRoute = ApiPublicHooksDailyPollRouteImport.update({
  id: '/api/public/hooks/daily-poll',
  path: '/api/public/hooks/daily-poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/api/ig-avatar': typeof ApiIgAvatarRoute
  '/app/add': typeof AppAddRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/standings': typeof AppStandingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/app/': typeof AppIndexRoute
  '/api/avatar/$': typeof ApiAvatarSplatRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/group/$id': typeof AppGroupIdRoute
  '/app/match/$id': typeof AppMatchIdRoute
  '/api/public/hooks/daily-poll': typeof ApiPublicHooksDailyPollRoute
  '/api/public/hooks/match-expiry': typeof ApiPublicHooksMatchExpiryRoute
  '/api/public/hooks/weekly-superlative': typeof ApiPublicHooksWeeklySuperlativeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/api/ig-avatar': typeof ApiIgAvatarRoute
  '/app/add': typeof AppAddRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/standings': typeof AppStandingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/app': typeof AppIndexRoute
  '/api/avatar/$': typeof ApiAvatarSplatRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/group/$id': typeof AppGroupIdRoute
  '/app/match/$id': typeof AppMatchIdRoute
  '/api/public/hooks/daily-poll': typeof ApiPublicHooksDailyPollRoute
  '/api/public/hooks/match-expiry': typeof ApiPublicHooksMatchExpiryRoute
  '/api/public/hooks/weekly-superlative': typeof ApiPublicHooksWeeklySuperlativeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/api/ig-avatar': typeof ApiIgAvatarRoute
  '/app/add': typeof AppAddRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/standings': typeof AppStandingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/app/': typeof AppIndexRoute
  '/api/avatar/$': typeof ApiAvatarSplatRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/group/$id': typeof AppGroupIdRoute
  '/app/match/$id': typeof AppMatchIdRoute
  '/api/public/hooks/daily-poll': typeof ApiPublicHooksDailyPollRoute
  '/api/public/hooks/match-expiry': typeof ApiPublicHooksMatchExpiryRoute
  '/api/public/hooks/weekly-superlative': typeof ApiPublicHooksWeeklySuperlativeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/api/ig-avatar'
    | '/app/add'
    | '/app/matches'
    | '/app/messages'
    | '/app/notifications'
    | '/app/settings'
    | '/app/shop'
    | '/app/standings'
    | '/app/upgrade'
    | '/onboarding/quiz'
    | '/app/'
    | '/api/avatar/$'
    | '/app/chat/$id'
    | '/app/group/$id'
    | '/app/match/$id'
    | '/api/public/hooks/daily-poll'
    | '/api/public/hooks/match-expiry'
    | '/api/public/hooks/weekly-superlative'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/api/ig-avatar'
    | '/app/add'
    | '/app/matches'
    | '/app/messages'
    | '/app/notifications'
    | '/app/settings'
    | '/app/shop'
    | '/app/standings'
    | '/app/upgrade'
    | '/onboarding/quiz'
    | '/app'
    | '/api/avatar/$'
    | '/app/chat/$id'
    | '/app/group/$id'
    | '/app/match/$id'
    | '/api/public/hooks/daily-poll'
    | '/api/public/hooks/match-expiry'
    | '/api/public/hooks/weekly-superlative'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/api/ig-avatar'
    | '/app/add'
    | '/app/matches'
    | '/app/messages'
    | '/app/notifications'
    | '/app/settings'
    | '/app/shop'
    | '/app/standings'
    | '/app/upgrade'
    | '/onboarding/quiz'
    | '/app/'
    | '/api/avatar/$'
    | '/app/chat/$id'
    | '/app/group/$id'
    | '/app/match/$id'
    | '/api/public/hooks/daily-poll'
    | '/api/public/hooks/match-expiry'
    | '/api/public/hooks/weekly-superlative'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  ApiIgAvatarRoute: typeof ApiIgAvatarRoute
  OnboardingQuizRoute: typeof OnboardingQuizRoute
  ApiAvatarSplatRoute: typeof ApiAvatarSplatRoute
  ApiPublicHooksDailyPollRoute: typeof ApiPublicHooksDailyPollRoute
  ApiPublicHooksMatchExpiryRoute: typeof ApiPublicHooksMatchExpiryRoute
  ApiPublicHooksWeeklySuperlativeRoute: typeof ApiPublicHooksWeeklySuperlativeRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/quiz': {
      id: '/onboarding/quiz'
      path: '/onboarding/quiz'
      fullPath: '/onboarding/quiz'
      preLoaderRoute: typeof OnboardingQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/standings': {
      id: '/app/standings'
      path: '/standings'
      fullPath: '/app/standings'
      preLoaderRoute: typeof AppStandingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add': {
      id: '/app/add'
      path: '/add'
      fullPath: '/app/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ig-avatar': {
      id: '/api/ig-avatar'
      path: '/api/ig-avatar'
      fullPath: '/api/ig-avatar'
      preLoaderRoute: typeof ApiIgAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/match/$id': {
      id: '/app/match/$id'
      path: '/match/$id'
      fullPath: '/app/match/$id'
      preLoaderRoute: typeof AppMatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/group/$id': {
      id: '/app/group/$id'
      path: '/group/$id'
      fullPath: '/app/group/$id'
      preLoaderRoute: typeof AppGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/avatar/$': {
      id: '/api/avatar/$'
      path: '/api/avatar/$'
      fullPath: '/api/avatar/$'
      preLoaderRoute: typeof ApiAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-superlative': {
      id: '/api/public/hooks/weekly-superlative'
      path: '/api/public/hooks/weekly-superlative'
      fullPath: '/api/public/hooks/weekly-superlative'
      preLoaderRoute: typeof ApiPublicHooksWeeklySuperlativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/match-expiry': {
      id: '/api/public/hooks/match-expiry'
      path: '/api/public/hooks/match-expiry'
      fullPath: '/api/public/hooks/match-expiry'
      preLoaderRoute: typeof ApiPublicHooksMatchExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-poll': {
      id: '/api/public/hooks/daily-poll'
      path: '/api/public/hooks/daily-poll'
      fullPath: '/api/public/hooks/daily-poll'
      preLoaderRoute: typeof ApiPublicHooksDailyPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppStandingsRoute: typeof AppStandingsRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppGroupIdRoute: typeof AppGroupIdRoute
  AppMatchIdRoute: typeof AppMatchIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppStandingsRoute: AppStandingsRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppGroupIdRoute: AppGroupIdRoute,
  AppMatchIdRoute: AppMatchIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  ApiIgAvatarRoute: ApiIgAvatarRoute,
  OnboardingQuizRoute: OnboardingQuizRoute,
  ApiAvatarSplatRoute: ApiAvatarSplatRoute,
  ApiPublicHooksDailyPollRoute: ApiPublicHooksDailyPollRoute,
  ApiPublicHooksMatchExpiryRoute: ApiPublicHooksMatchExpiryRoute,
  ApiPublicHooksWeeklySuperlativeRoute: ApiPublicHooksWeeklySuperlativeRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
